#!/usr/bin/env bash
cd MARKSTG
echo -e "\e[33m            __ ___           \e[0m"
echo -e "\e[33m           |  \/  |          \e[0m"
echo -e "\e[33m           | |\/| |          \e[0m"
echo -e "\e[33m           \_|  |_|          \e[0m"
echo -e "\e[33m                                         \e[0m"
while(true) do
lua start.lua 
done
